### ISSUE TITLE
[Feature Request] Add A Generic IMessagePublisher

### ISSUE THREAD

**Issue by hwoodiwiss** [justeat/JustSaying#1052]
**Is your feature request related to a problem? Please describe.**

Not really a problem, this is more of a developer experience/ergonomic enhancement.

 I think a typed message publisher would provide an avenue to fail-fast in situations where publishers have not been configured correctly, and provides a more strongly typed API for publishing messages.

**Describe the solution you'd like**

From an ergonomics point of view, it would be nice to be able to inject an `IMessagePublisher<T> where T : Message` and have that indicate to developers and maintainers the type of message that should be published from that code.

I would suggest adding an `IMessagePublisher<T>` :

```c#
public interface IMessagePublisher<in T> : IInterrogable, IStartable
    where T : Message
{
    Task PublishAsync(T message, CancellationToken cancellationToken);
    Task PublishAsync(T message, PublishMetadata metadata, CancellationToken cancellationToken);
}
```

With a single implementation (`TypedMessagePublisher<T>`) that passes calls through to the existing IMessagePublisher.
This can then be injected as an open generic singleton into the DI library extensions JustSaying provides.

On construction, the `TypedMessagePublisher` could also check to see if it's generic type has been registered on the `IMessagePublisher`

**Describe alternatives you've considered**

The alternative would be to continue using IMessagePublisher as is.

I've prototyped this here: [diff](https://github.com/justeat/JustSaying/compare/main...hwoodiwiss:JustSaying:hwoodiwiss/add-typed-publisher)

**Comment by martincostello** [comment]
There's a similar piece of code we have in an internal library (I'll Slack you the link after I write this) where the generic bit is the _publish_ rather than the publisher.

In the case where you want to publish multiple messages in the same method/class, it removes the need for you to inject N instances of a publisher. We have use cases internally where we need to publish versioned variants of essentially the same message and in such scenarios you could use one publisher but still get the generics, rather than need multiple publishers.
