### ISSUE TITLE
Publisher is not the same as subscriber

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/JustSaying#243]
We have many projects that are web apis that publish messages to SNS/SQS but never receive and handle any messages.

Would it be a good idea to separate out the much lighter-weight publishing code so that a project can just use this part?

To clarify: Message subscribers often also publish messages. But message publishers often never subscribe, as a common pattern is to publish a message on receiving a http request.

**Comment by stuart-lang** [comment]
I'm personally am not too convinced on the benefits of separating this into 2 packages, the assemblies are relatively small. However when we move to core it will mean that you only need the AWS SQS package for subscribers, and AWS SNS package for publishing, loading 1 less assembly would be nice.

That's if we refactor the topics and queue creation code so that subscribers aren't trying to create topics, which I think is a bit bizarre.

**Comment by payman81** [comment]
keeping them together has no impact in runtime. The only benefit is potentially fewer libs when publish is all you want. 
Also, maintaining a lighter weight version as well as full version is bound to have some overhead in maintenance. I'm not sure if the benefit outweighs the maintenance overhead.

**Comment by dariusdamalakas** [comment]
@AnthonySteele not sure what is the target benefit here. We do run into this when we just consume messages but not publish, or just publish but not consume, but this works fine.

**Comment by AnthonySteele** [comment]
OK, if you don't think there's much benefit then lets shelve this.
