### ISSUE TITLE
Events, commands, messages..

### ISSUE THREAD

**Issue by JefClaes** [justeat/JustSaying#268]
Examples in the readme focus on publishing events. This makes sense given the project name.. 

However, if I would be interested in queueing of commands (JustDo) inside of a component (for example; CancelOrder), is there a way to achieve this using JustSaying? 
How does JustEat handle these scenarios? Or do they just publish a command, and don't care that it becomes an SNS topic and could be subscribed to by more than one component?

**Comment by slang25** [comment]
@JefClaes great question!

My understanding is that JustSaying was built primarily with pub/sub in mind, and we have an implementation of INamingStrategy in JustEat that gives us globally namespaced topics, and queues that include the component name. We do in places want and use commands, in that scenario we name the message type appropriately, so that it reads as an instruction, and ends in Command so that it's obvious, but you are right other components could subscribe to this. I found [this post](https://lostechies.com/jimmybogard/2012/12/20/messaging-semantics-ownership/) to be very useful regarding messaging semantics.

We also have the ability to publish straight to a queue, point-to-point, although I haven't come across where this has been used.

I have been giving this some thought over the last few weeks. Other similar libraries have a Publish method for events and a Send method for Commands. We could then on the consumer side both listen to events, and handle commands, in practice there is no difference it's all just sending messages and semantics.

However one of the bits I love most about this library is its simplicity, there is a trade off between simplicity and having a flexible api where you can make it do exactly what you need, or event a fuller api that lets you better express your intent and accounts for every possible scenario you might want to express (for example, see [this post](https://serialseb.com/blog/2016/08/18/architecture-in-code/ ) which is directed pretty much at this library)

That's my thoughts, I'd like to hear others and are people interested in adding more messaging semantics to this library?

**Comment by payman81** [comment]
Point-to-point subscription is the closest thing to what you're after that JustSaying offers.
In point-to-point subscription, your publisher directly drops the message in subscriber's queue.

CreateMeABus
.InRegion(...)
.WithSqsMessagePublisher<CommandMessage>(...)

**Comment by brainmurphy** [comment]
Yeah, the SQS publish was explicitly written in order to use JustSaying as a command bus. There's a post about it here: https://tech.just-eat.com/2014/11/26/outsourcing-troublesome-tasks-to-an-ec2-worker 😉

**Comment by JefClaes** [comment]
Thanks for the quick reply everyone!

I had looked into the point-to-point subscription but couldn't get it to work at first. Anyways, a second try (knowing I was on the right track), it works as expected.

@slang25 I have experience with NServiceBus and its opinionated API, so I have also gotten used to the Send and Publish semantics as well.. TBH I've settled on making two instances of the bus (eventBus/commandBus) which carries enough semantic meaning for now.

Consider this issue closed :+1:
