### ISSUE TITLE
Switch to async where we can for JustSaying 6?

### ISSUE THREAD

**Issue by adammorr** [justeat/JustSaying#392]
I was thinking it might be a good thing to do for JustSaying 6 if anyone else agrees?

We already have the internal way of doing this which we could use a base for this work so I'm happy to pick it up 👍 

It would involve changes to the API.

**Comment by martincostello** [comment]
I think it would be a good idea to do this to reduce future breaking changes, but isn't this getting a bit late-in-the-day for 6?

**Comment by AnthonySteele** [comment]
What do we still have that's not async? It is late in the day for  v6 if it changes api surface.

**Comment by slang25** [comment]
I agree that it's too late in the day for v6. The parts that are still blocking on async happens in the startup, essentially we need to change the fluent api to be a builder with a `.BuildAsync()` method you can await.

We have had a couple of stabs at this and never finished it because we either had a release coming out, or couldn't decide on how much to change.

Whatever we do would be a breaking change (unless there was an entirely new side-by-side API, I don't like the added complexity), so we could try to make the API more intuitive at the same time.

Here are the previous attempts:
https://github.com/justeat/JustSaying/pull/330
https://github.com/justeat/JustSaying/pull/327

**Comment by adammorr** [comment]
Yeah, what @stuart-lang said.

I feel like this answers the question which is hold off as part of v6 and have a proper discussion on the correct way forward 🎉

**Comment by AnthonySteele** [comment]
Reworking the builder could be big feature for V7
