### ISSUE TITLE
Prevent JustSaying creating queues and notification subscriptions

### ISSUE THREAD

**Issue by SeanFarrow** [justeat/JustSaying#466]
Does JustSaying provide a way to prevent queue creation and notification subscription?

If it doesn't this would be a nice feature to add. We are using a devops based workflow and I'd like to prevent queues/subscriptions being created in production.

**Comment by martincostello** [comment]
This isn't currently supported as far as I'm aware, but could be something we consider adding to version 7.0.0.

**Comment by martincostello** [comment]
Something like `...((options) => options.WithNoQueueCreation())`?

**Comment by SeanFarrow** [comment]
That works for me, do we need to consider topic creation and subscription?
I’m happy to help write this, once I know where the fluent api lives.

**Comment by slang25** [comment]
A proposed 7.0 api is here: https://github.com/justeat/JustSaying/pull/431
and it's looking great IMO. Yes we'd want to be able to suppress the creation queues, topics, and subscriptions.

**Comment by martincostello** [comment]
I think we'd certainly be open to your contributions @SeanFarrow once the agreed initial shape of the new API gets merged into the `master` branch.

**Comment by SeanFarrow** [comment]
@MartinCostello,
When is this likely to happen? There’s no rush, I just need to prioritise things this end.

**Comment by martincostello** [comment]
We don't have any firm dates at the moment, but there's various bits of refactoring/redesign and new features wanted for 7.0, so we're likely talking in the order of months.

**Comment by SeanFarrow** [comment]
Ok, that’s fine, can you let me know when I’m safe to start contributing.

**Comment by martincostello** [comment]
Sure, will do.

**Comment by shaynevanasperen** [comment]
@SeanFarrow In the meantime, if you're eager to contribute, we'd certainly appreciate your review/feedback on #431 😄

**Comment by SeanFarrow** [comment]
Are we at a point in any refactoring where this could be contributed?

**Comment by JarrodJ83** [comment]
I've been looking into this a bit as our IT group doesn't want our software dynamically modifying our infrastructure. 

I looked into doing this as outlined above by simply adding a method to "Suppress" the infrastructure creation/modification. It doesn't look like it will be this easy as the infrastructure stuff seems pretty tightly coupled to the building of the bus. As far as I can tell there would have to be several places where this flag would need passed and evaluated repeatedly which doesn't seem optimal. 

That said I was going to take a look at possibly separating the two concerns and wanted your feedback. My initial high level thought is that we could make it so that you configure a bus and then have some kind of IVerifyBusInfrastructure that takes an instance of a bus or bus builder, looks at the configuration, and does all the work to make sure the infrastructure is there. 

I'm going to start exploring this in more detail, but if you have any high level thoughts I'd love to hear them.

- Jarrod

**Comment by martincostello** [comment]
Our current plan is to complete a rework of our test suite, at which point we're going to start fleshing out the new "bus builder" configuration and removing the `CreateMeABus` infrastructure as part of v7.

At a _very_ high level we'd want something on the bus builder stuff somewhere to allow you to opt-out, but beyond that I'd imagine the implementation details for that would be up for discussion.

The Just Eat team usually meet weekly on Fridays, so unless anyone else chips in here before then, I'll bring this up for discussion at our meeting later this week.

**Comment by slang25** [comment]
In addition to a suppress flag, it would be interesting if after you do your configuration you could call a method (instead of `StartListening` or whatever it's called) that would give you the CloudFormation JSON/YAML for the configured queues and topics.

This way you could expose within your solution to a command line tool that you could run ad-hoc, or as part of CI.

**Comment by JarrodJ83** [comment]
@martincostello thanks for the information. I'll wait to hear more from you before I spend too much time on it.

**Comment by SeanFarrow** [comment]
Hi,

Are we at a point within the v7 development cycle where this can/needs to be worked on?
Thanks,
Sean.

**Comment by martincostello** [comment]
Hi @SeanFarrow - sorry for the inactivity on this issue and JustSaying in general of late.

If you still want to add this in, I'd suggest not waiting for us and opening a PR at your convenience.

**Comment by SeanFarrow** [comment]
@martincostello I'm just looking at this again. What is the best place to surface the configuration. Iask this as you are looking to get rid of some interfaces.

Thanks,
Sean.

**Comment by martincostello** [comment]
If you aim some for the “builder” things to be the main way to configure, the rest for the plumbing can just go wherever seems sensible as we’ll the ripping the old interfaces out and some point and moving things around.

**Comment by BondarYuriy** [comment]
@martincostello 
Hi
What is the state of this issue? We would really want to have this functionality since currently JastSaying require write permissions for message listener creation (since it always tries to create topics, queues and subscriptions). If it was no implementation yet we may contribute and propose simple solution:
  -	Extend SqsBasicConfiguration with the additional parameter let say “ConfigureTopicsAndQueues” with the default value “true” so do not change existed behavior (for those who relies on it)
  -	Internally, depending of the parameter value, either tries to create and configure queue or just gets and use existed  

What would you say? We can prepare necessary changes and gives them to you for reviewing.

**Comment by SeanFarrow** [comment]
Hi,

I’ll be having a look at finishing this next week.
Thanks,
Sean.

**Comment by SeanFarrow** [comment]
@BondarYuriy @martincostello Do we want ot be able ot configure queue and topic creation globally or on a per queue/topic basic?
Also, what about subscribing a queue to a topic, should this be configurable too?

Thanks,
Sean.

**Comment by martincostello** [comment]
I guess both would be good, though if that's too difficult it could be made per-"thing" (queue, topic, subscription, etc.).

The default would be to always create as we do today.

**Comment by SeanFarrow** [comment]
﻿
That makes sense, however my only question to follow up is what do we do if someone has said they don’t want the queue created but they want the topic and the queue subscribed? I don’t think subscribing a non-existent queue to a topic is doable within AWS, but feel free to correct my understanding.

Finally, what sort of tests do we want around this? I can’t seem to find tests for the current queue creation logic

Sent from my iPhone


On 18 Feb 2020, at 09:44, Martin Costello <notifications@github.com> wrote:
﻿

I guess both would be good, though if that's too difficult it could be made per-"thing" (queue, topic, subscription, etc.).

The default would be to always create as we do today.

**Comment by SeanFarrow** [comment]
@martincostello I'm now starting work on this.
Please could you assign this to me.
Should we split the queue/topic creation and subscription logic in to different classes/interfaces?
Also, what should we do if a topic doesn't exist and a user tries to publish?

**Comment by martincostello** [comment]
For interfaces it seems sensible to segregate subscriptions and publishing to me. There's no reason the same class couldn't implement both though - I guess it depends on how the changes to make this work come about.

Regarding publishing if the topic doesn't exist, I'd just attempt to do it anyway and allow the exception from the AWS SDK to propagate back to the caller. Otherwise we'd have to add additional code to try and reason why it doesn't, which isn't guaranteed to be accurate anyway as I think if there's a permissions issue AWS give you a 404 rather than a 401/403 to prevent information leakage, so you might _think_ it doesn't exist when really it's that the IAM setup is wrong.

**Comment by martincostello** [comment]
> Should we be testing the queue/subscription creation logic?

If it's not _very difficult_ to do so, then yes we should test it somehow, even if it's just unit tests and integration tests with the Docker emulator.
