### ISSUE TITLE
Integration Tests not working with latest goaws

### ISSUE THREAD

**Issue by slang25** [justeat/JustSaying#494]
The latest version of goaws has been pushed to docker hub, it contains some really nice fixes (we might be able to enable more tests). However currently it has broken our tests, so we either need to pin the version or fix them.

See here:
https://travis-ci.org/justeat/JustSaying/jobs/473402360

I'll do some investigating.

**Comment by slang25** [comment]
It seems to be picking up the `Local` environment config, not `Dev` ([see here](https://github.com/p4tin/goaws/blob/c0c3d207a7c5e8a03460e034f53bf71b91a3eaf3/app/conf/goaws.yaml#L3)), so we are getting queue urls with `...goaws.com/...` in.

**Comment by martincostello** [comment]
I had this problem locally a week or so ago actually running it locally on my work laptop because Docker is messed up on it.

In my case I had to explicitly tell it were the `goaws.yaml` file was in WSL as it didn't seem to be picking the location up for itself, so then it was generating queue URIs like `http://:/foo`, and causing exceptions from `Uri.ctor()`.

**Comment by martincostello** [comment]
#495 works around this by pinning the version, but we should look into what's wrong and fix it or raise an issue against goaws.

**Comment by slang25** [comment]
Agreed, that was just to unblock us. I think it is finding the config but selecting the wrong env. I'll create an image with our own config and see I can get it working.  Probably tonight

**Comment by martincostello** [comment]
@slang25 I guess this is done now?

**Comment by slang25** [comment]
Thanks, fixed in #496
