### ISSUE TITLE
Can I Set the Error queue Name ?

### ISSUE THREAD

**Issue by jovi-Li** [justeat/JustSaying#559]
I want my Queues Use the same error queue

**Comment by martincostello** [comment]
From looking through the code, it looks like you can only change the name by creating a derived `ErrorQueue` class and using the protected setter on the `QueueName` property to change the name. You'd then need to derive from `SqsQueueByName` and use the protected setter on the `ErrorQueue` property to change it.

This is something we can consider improving for v7 so it's just a quick bit of custom configuration, rather than all this additional complexity required to work-around the hard-coded queue name suffix of `_error`.

https://github.com/justeat/JustSaying/blob/88f96637690f765e4a2c7cfaaee446d764f40729/JustSaying/AwsTools/ErrorQueue.cs#L18

https://github.com/justeat/JustSaying/blob/88f96637690f765e4a2c7cfaaee446d764f40729/JustSaying/AwsTools/MessageHandling/SqsQueueBase.cs#L18

https://github.com/justeat/JustSaying/blob/88f96637690f765e4a2c7cfaaee446d764f40729/JustSaying/AwsTools/MessageHandling/SqsQueueByName.cs#L22

https://github.com/justeat/JustSaying/blob/88f96637690f765e4a2c7cfaaee446d764f40729/JustSaying/AwsTools/MessageHandling/SqsQueueBase.cs#L20

**Comment by jovi-Li** [comment]
thanks
