### ISSUE TITLE
When the bus starts listening, it starts listening twice

### ISSUE THREAD

**Issue by petemounce** [justeat/JustSaying#59]
When I call `bus.StartListening()`, I can see that be logged twice.

I expect it to only be started once - or is this a case of logging being misworded?

**Comment by payman81** [comment]
I have noticed that every time JustSaying polls for new incoming messages it logs starts listening. I think the solution is to reword the logging message slightly to suggest that this is a recurring event.

**Comment by brainmurphy** [comment]
If you're using multiple regions, then JustSayingFluently.StartListening() will start listening on every region that you've specified. Some clearer wording would be welcome if this sounds confusing.

**Comment by payman81** [comment]
@petemounce / @brainmurphy Any PR to improve logging is welcome. cheers.

**Comment by dariusdamalakas** [comment]
@petemounce , thats because the queue is being checked for existence multiple times, I have raised #86 for this.  Also [SqsQueueByNameBase.Exists()](https://github.com/justeat/JustSaying/blob/fcb9e827c52cf93560bd69ebadfb4a76cbfd4d15/JustSaying.AwsTools/SqsQueueByNameBase.cs#L26) incorrectly says that is it polling for queue, when in fact it is not polling, but trying to list the queues, that's how it is checking whether they exist or not.
